"""Fetch + stitch a dark basemap for the 3D city ground.

Pulls CARTO ``dark_nolabels`` raster tiles (© OpenStreetMap, © CARTO) covering
the RentSafeTO building extent, stitches them, and writes:
  • frontend/public/toronto-basemap.jpg  — the committed map image
  • frontend/src/lib/basemap.ts           — its exact WGS84 geo-bounds

One-time online step; the runtime then reads the local image (offline).

    PYTHONPATH=backend python -m openhouse.scripts.ingest_basemap
"""

from __future__ import annotations

import io
import math
import time
import urllib.request
from pathlib import Path

from openhouse.data.store import BuildingStore

Z = 12
TILE = 256
PAD = 0.02  # degrees of padding around the building bbox
SUBS = ["a", "b", "c", "d"]
_ROOT = Path(__file__).resolve().parents[3]
OUT_IMG = _ROOT / "frontend" / "public" / "toronto-basemap.jpg"
OUT_TS = _ROOT / "frontend" / "src" / "lib" / "basemap.ts"


def lonlat_to_tile(lon: float, lat: float, z: int) -> tuple[float, float]:
    n = 2 ** z
    x = (lon + 180.0) / 360.0 * n
    y = (1.0 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2.0 * n
    return x, y


def tile_nw(x: int, y: int, z: int) -> tuple[float, float]:
    """North-west corner lon/lat of tile (x, y, z)."""
    n = 2 ** z
    lon = x / n * 360.0 - 180.0
    lat = math.degrees(math.atan(math.sinh(math.pi * (1.0 - 2.0 * y / n))))
    return lon, lat


def main() -> None:
    from PIL import Image

    store = BuildingStore()
    row = store._conn.execute(
        "SELECT MIN(latitude), MAX(latitude), MIN(longitude), MAX(longitude) "
        "FROM buildings WHERE latitude IS NOT NULL AND longitude IS NOT NULL"
    ).fetchone()
    store.close()
    min_lat, max_lat, min_lng, max_lng = (row[0] - PAD, row[1] + PAD, row[2] - PAD, row[3] + PAD)

    x0, y0 = lonlat_to_tile(min_lng, max_lat, Z)  # NW
    x1, y1 = lonlat_to_tile(max_lng, min_lat, Z)  # SE
    xmin, xmax = int(math.floor(x0)), int(math.floor(x1))
    ymin, ymax = int(math.floor(y0)), int(math.floor(y1))
    cols, rows = xmax - xmin + 1, ymax - ymin + 1
    print(f"bbox lat {min_lat:.4f}..{max_lat:.4f}  lng {min_lng:.4f}..{max_lng:.4f}")
    print(f"fetching {cols}×{rows} = {cols * rows} tiles at z{Z} …")

    img = Image.new("RGB", (cols * TILE, rows * TILE), (8, 10, 8))
    ok = 0
    for i, x in enumerate(range(xmin, xmax + 1)):
        for j, y in enumerate(range(ymin, ymax + 1)):
            sub = SUBS[(i + j) % len(SUBS)]
            url = f"https://{sub}.basemaps.cartocdn.com/dark_nolabels/{Z}/{x}/{y}.png"
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "Meraklis/1.0 (Toronto civic demo)"})
                data = urllib.request.urlopen(req, timeout=20).read()
                img.paste(Image.open(io.BytesIO(data)).convert("RGB"), (i * TILE, j * TILE))
                ok += 1
            except Exception as exc:  # noqa: BLE001
                print("  ! tile", x, y, exc)
            time.sleep(0.02)

    w_lng, n_lat = tile_nw(xmin, ymin, Z)
    e_lng, s_lat = tile_nw(xmax + 1, ymax + 1, Z)

    OUT_IMG.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT_IMG, "JPEG", quality=82)
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(
        "// Generated by openhouse.scripts.ingest_basemap — dark Toronto basemap for the 3D city.\n"
        "export const BASEMAP = {\n"
        '  src: "/toronto-basemap.jpg",\n'
        f"  minLat: {s_lat:.6f}, maxLat: {n_lat:.6f}, minLng: {w_lng:.6f}, maxLng: {e_lng:.6f},\n"
        '  attribution: "\\u00A9 OpenStreetMap contributors \\u00A9 CARTO",\n'
        "};\n"
    )
    print(f"✅ {ok}/{cols * rows} tiles → {OUT_IMG} ({OUT_IMG.stat().st_size // 1024} KB)")
    print(f"   bounds lat {s_lat:.5f}..{n_lat:.5f}  lng {w_lng:.5f}..{e_lng:.5f} → {OUT_TS}")


if __name__ == "__main__":
    main()
