// Generated by openhouse.scripts.ingest_basemap — dark Toronto basemap for the 3D city.
export const BASEMAP = {
  src: "/toronto-basemap.jpg",
  minLat: 43.516689, maxLat: 43.834527, minLng: -79.716797, maxLng: -79.101562,
  attribution: "\u00A9 OpenStreetMap contributors \u00A9 CARTO",
};
